version: '3.6'
networks:
    dbs-network:
        name: dbs-network
        driver: bridge

services:
    minio:
        container_name: srv-minio
        hostname: minio
        image: minio/minio:${MINIO_VERSION}
        restart: always
        networks:
            - dbs-network
        ports:
            - ${MINIO_PORT}:9000
        environment:
            - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
            - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
        volumes:
            - ./data/minio-data:/data
        command: server /data
    pgsql:
        container_name: srv-pgsql
        image: postgres:${POSTGRES_VERSION}
        restart: always
        volumes:
            - ./data/pgsql-data:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - dbs-network
    redis:
        container_name: srv-redis
        image: bitnami/redis:${REDIS_VERSION}
        restart: always
        ports:
            - ${REDIS_PORT}:6379
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        volumes:
            - ./data/redis-data:/bitnami/redis/data
        networks:
            - dbs-network

